
package travel;

import java.util.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

/**
 * This class represents the View which will reflect the model objects TravelFormModel and TravelComboBoxModel.
 *
 * <PRE>
 * Filename:         TravelItineraryView.java
 *
 * Description:      This serves as the view for this code diagnostic.  This is the GUI representation of the TravelFormModel object.
 * 					 The user updates the model using this display by using the JComponents.  This view accepts both the TravelFormModel
 *					 and the TravelComboBoxModel objects.  This class makes use of Listeners for user interaction that update the model in
 *					 order for a "pull model" of the MVC to be implemented..
 *
 * Instantiated By:  TravelForm.java
 *
 * Aggregation Of:	 MainController.java
 *
 * Maintainer:       A. Cave
 *
 * Version:          0.102
 *
 * Lasted Modified:  04/21/2010  by: A. Cave
 *
 * Changes Made -------
 * 0.100: A. Cave   Initial Version.
 * 0.101: A. Cave   Removed main() program to the TravelForm class.
 * 0.102: A. Cave   Removed the listeners and put them into the MainController class.
 * </PRE>
  */
  public class TravelItineraryView extends javax.swing.JFrame {

	    // Variables declaration
	    private javax.swing.JLabel departureDateLabel;
	    private javax.swing.JComboBox departureDayComboBox;
	    private javax.swing.JComboBox departureMonthComboBox;
	    private javax.swing.JComboBox departureSettingComboBox;
	    private javax.swing.JComboBox departureYearComboBox;
	    private javax.swing.JLabel fromLabel;
	    private javax.swing.JTextField fromTextBox;
	    private javax.swing.JButton submitButton;
	    private javax.swing.JComboBox passengersComboBox;
	    private javax.swing.JLabel passengersLabel;
	    private javax.swing.JLabel returnDateLabel;
	    private javax.swing.JComboBox returnDayComboBox;
	    private javax.swing.JComboBox returnMonthComboBox;
	    private javax.swing.JComboBox returnSettingComboBox;
	    private javax.swing.JComboBox returnYearComboBox;
	    private javax.swing.JLabel toLabel;
	    private javax.swing.JTextField toTextBox;
	    // End of variables declaration//GEN-END:variables


    /** Creates new form TravelItineraryView */
    public TravelItineraryView()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

		//these following variables are used for getting the screen dimensions and used for centering the application
		java.awt.Dimension dm = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		int screenWidth = (int) dm.getWidth();
		int screenHeight = (int) dm.getHeight();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel Form");

		//these methods create the necessary labels, event listeners, JComponent initialization and so forth.
		//Refer to the appropriate method at the bottom of this page for a more detailed explanation.
        this.initLabels();
        this.initTextFields();
        this.initComboBoxes();
        this.initButtons();

		//Put the form together.
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnDateLabel)
                .addContainerGap(594, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passengersLabel)
                .addContainerGap(598, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(submitButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fromLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fromTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(toLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(toTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(departureDateLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(returnMonthComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 123, Short.MAX_VALUE)
                                .addComponent(departureMonthComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 123, Short.MAX_VALUE)
                                .addComponent(passengersComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 123, Short.MAX_VALUE))
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(returnDayComboBox, 0, 90, Short.MAX_VALUE)
                                .addComponent(departureDayComboBox, 0, 90, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(returnYearComboBox, 0, 100, Short.MAX_VALUE)
                                .addComponent(departureYearComboBox, 0, 100, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(returnSettingComboBox, 0, 114, Short.MAX_VALUE)
                                .addComponent(departureSettingComboBox, 0, 114, Short.MAX_VALUE)))))
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromLabel)
                    .addComponent(fromTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toLabel)
                    .addComponent(toTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureDateLabel)
                    .addComponent(departureMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departureSettingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departureYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departureDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnDateLabel)
                    .addComponent(returnMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnSettingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengersLabel)
                    .addComponent(passengersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        	pack();  //render the GUI
        	int guiWidth = (int) this.getSize().getWidth();
			int guiHeight = (int) this.getSize().getHeight();

			//set the GUI to the middle of the screen.
        	this.setLocation((screenWidth - guiWidth)/2,(screenHeight-guiHeight)/2);
    }// </editor-fold>//GEN-END:initComponents

	/*
	* This private method initializes the Labels to be displayed on the GUI.
	*/
    private void initLabels()
    {
        fromLabel = new javax.swing.JLabel("From:");
        toLabel = new javax.swing.JLabel("To:");
        departureDateLabel = new javax.swing.JLabel("Departure Date:");
        returnDateLabel = new javax.swing.JLabel("Return Date:");
        passengersLabel = new javax.swing.JLabel("Passengers:");

	}

	/*
	* This method instantiates the Text Fields that model the To and From Locations of the TravelFormModel object.
	*/
    private void initTextFields()
    {
		  fromTextBox = new javax.swing.JTextField();
		  fromTextBox.setColumns(60);
		  toTextBox = new javax.swing.JTextField();
		  toTextBox.setColumns(60);
	}

	/*
	* This method instantiates the ComboBoxes object references that will contain and display the Combo Box values that are
	* provided (from the TravelComboBoxModel class) via the Main Controller.
	*/
	private void initComboBoxes()
	{
		 departureMonthComboBox = new javax.swing.JComboBox();

		 departureDayComboBox = new javax.swing.JComboBox();

		 departureYearComboBox = new javax.swing.JComboBox();

		 departureSettingComboBox = new javax.swing.JComboBox();

		 returnMonthComboBox = new javax.swing.JComboBox();

		 returnDayComboBox = new javax.swing.JComboBox();

		 returnYearComboBox = new javax.swing.JComboBox();

		 returnSettingComboBox = new javax.swing.JComboBox();

		 passengersComboBox = new javax.swing.JComboBox();
	}

	/*
	* This method instantiates the JButton that submits the TravelFormInformation object.
	*/
	private void initButtons()
	{
		submitButton = new javax.swing.JButton("Submit");
	}

	/**
	* This method returns the To Location JTextField Swing Component to the Controller.
	*/
	public JTextField getToLocationTextField()
	{
		return toTextBox;
	}

	/**
	* This method returns the From Location JTextField Swing Component to the Controller.
	*/
	public JTextField getFromLocationTextField()
	{
		return fromTextBox;
	}

	/**
	* This method returns the Departure Month JComboBox Swing Component to the Controller.
	*/
	public JComboBox getDepartureMonthDropDown()
	{
		return departureMonthComboBox;
	}

	/**
	* This method returns the Departure Day JComboBox Swing Component to the Controller.
	*/
	public JComboBox getDepartureDayDropDown()
	{
		return departureDayComboBox;
	}

	/**
	* This method returns the Departure Year JComboBox Swing Component to the Controller.
	*/
	public JComboBox getDepartureYearDropDown()
	{
		return departureYearComboBox;
	}

	/**
	* This method returns the Departure Time Setting JComboBox Swing Component to the Controller.
	*/
	public JComboBox getDepartureSettingDropDown()
	{
		return departureSettingComboBox;
	}

	/**
	* This method returns the Return Month JComboBox Swing Component to the Main Controller.
	*/
	public JComboBox getReturnMonthDropDown()
	{
		return returnMonthComboBox;
	}

	/**
	* This method returns the Return Day JComboBox Swing Component to the Controller.
	*/
	public JComboBox getReturnDayDropDown()
	{
		return returnDayComboBox;
	}

	/**
	* This method returns the Return Year JComboBox Swing Component to the Controller.
	*/
	public JComboBox getReturnYearDropDown()
	{
		return returnYearComboBox;
	}

	/**
	* This method returns the Return Time Setting JComboBox Swing Component to the Controller.
	*/
	public JComboBox getReturnSettingDropDown()
	{
		return returnSettingComboBox;
	}

	/**
	* This method returns the Passenger JComboBox Swing Component to the Controller.
	*/
	public JComboBox getPassengerDropDown()
	{
		return passengersComboBox;
	}

	/**
	* This method returns the Submit JButton Swing Component to the Controller.
	*/
	public JButton getSubmitButton()
	{
		return submitButton;
	}
}
